version: '3.7'

services:
  octodule:
    networks:
      - octo
    build: .
    restart: always
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      RABBIT_MQ_HOST: ${RABBIT_MQ_HOST}
networks:
  octo:
    external: true