on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: 👃 Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🙀 Analyze code
        run: npm run lint

      - name: ✊ Run tests
        run: npm test
